# Generated by Django 4.2.6 on 2023-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=50)),
                ('link', models.URLField(default=None, null=True)),
            ],
        ),
    ]
