# Generated by Django 4.2.6 on 2023-11-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest_name', models.CharField(max_length=255)),
                ('fest_img', models.CharField(max_length=255)),
                ('fest_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('sub_title', models.CharField(blank=True, default=None, max_length=255)),
                ('img', models.CharField(blank=True, default=None, max_length=255)),
                ('price', models.CharField(blank=True, default=None, max_length=255)),
                ('sub_price', models.CharField(blank=True, default=None, max_length=255)),
                ('discount', models.CharField(blank=True, default=None, max_length=255)),
                ('duration', models.CharField(blank=True, default=None, max_length=255)),
                ('day1', models.CharField(blank=True, default=None, max_length=255)),
                ('day2', models.CharField(blank=True, default=None, max_length=255)),
                ('day3', models.CharField(blank=True, default=None, max_length=255)),
                ('day4', models.CharField(blank=True, default=None, max_length=255)),
                ('place1', models.CharField(blank=True, default=None, max_length=255)),
                ('place2', models.CharField(blank=True, default=None, max_length=255)),
                ('place3', models.CharField(blank=True, default=None, max_length=255)),
                ('place4', models.CharField(blank=True, default=None, max_length=255)),
                ('hotel1', models.CharField(blank=True, default=None, max_length=255)),
                ('hotel3', models.CharField(blank=True, default=None, max_length=255)),
                ('hotel4', models.CharField(blank=True, default=None, max_length=255)),
            ],
        ),
    ]
