# Generated by Django 4.2.6 on 2023-11-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_package_city_package_hotel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='details',
            field=models.TextField(blank=True, default=None),
        ),
    ]
