# Generated by Django 4.2.6 on 2023-11-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_search_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='img',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
