# Generated by Django 4.2.6 on 2023-11-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_search_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='img',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
