# Generated by Django 4.2.6 on 2023-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_search_img_alter_search_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='link',
            field=models.URLField(default=None, null=True),
        ),
    ]
