# Generated by Django 4.2.6 on 2023-11-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_search_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('month', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('departing_from', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('no_people', models.CharField(max_length=50)),
            ],
        ),
    ]
